export const WHATSAPP_AUTO_CREATE_THRESHOLD = 0.86;
export const WHATSAPP_CONFIRMATION_THRESHOLD = 0.7;
export const WHATSAPP_MAX_TEXT_LENGTH = 1500;
export const WHATSAPP_MAX_MEDIA_ITEMS = 4;
export const WHATSAPP_MAX_MEDIA_BYTES = 5 * 1024 * 1024;

export const WHATSAPP_ALLOWED_MEDIA_MIME_TYPES = new Set([
  "image/jpeg",
  "image/jpg",
  "image/png",
  "application/pdf",
]);

export const WHATSAPP_CANDIDATE_STATUS = {
  AUTO_CREATED_PENDING_REVIEW: "auto_created_pending_review",
  AWAITING_USER_CONFIRMATION: "awaiting_user_confirmation",
  AWAITING_ACCOUNT_SELECTION: "awaiting_account_selection",
  NEEDS_CLARIFICATION: "needs_clarification",
  REVIEWED_CONFIRMED: "reviewed_confirmed",
  REVIEWED_CORRECTED: "reviewed_corrected",
  REVIEWED_REMOVED: "reviewed_removed",
  CONFIRMED: "confirmed",
  IGNORED: "ignored",
  IGNORED_PATTERN: "ignored_pattern",
} as const;

export const WHATSAPP_OPEN_CANDIDATE_STATUSES = [
  WHATSAPP_CANDIDATE_STATUS.AWAITING_USER_CONFIRMATION,
  WHATSAPP_CANDIDATE_STATUS.AWAITING_ACCOUNT_SELECTION,
  WHATSAPP_CANDIDATE_STATUS.NEEDS_CLARIFICATION,
];

export const WHATSAPP_REVIEW_QUEUE_STATUSES = [
  WHATSAPP_CANDIDATE_STATUS.AUTO_CREATED_PENDING_REVIEW,
  WHATSAPP_CANDIDATE_STATUS.AWAITING_USER_CONFIRMATION,
  WHATSAPP_CANDIDATE_STATUS.AWAITING_ACCOUNT_SELECTION,
  WHATSAPP_CANDIDATE_STATUS.NEEDS_CLARIFICATION,
  WHATSAPP_CANDIDATE_STATUS.REVIEWED_CONFIRMED,
  WHATSAPP_CANDIDATE_STATUS.REVIEWED_CORRECTED,
  WHATSAPP_CANDIDATE_STATUS.REVIEWED_REMOVED,
  WHATSAPP_CANDIDATE_STATUS.CONFIRMED,
  WHATSAPP_CANDIDATE_STATUS.IGNORED,
  WHATSAPP_CANDIDATE_STATUS.IGNORED_PATTERN,
];

export function sanitizeIncomingText(text?: string) {
  return String(text || "")
    .replace(/\u0000/g, "")
    .replace(/\s+/g, " ")
    .trim()
    .slice(0, WHATSAPP_MAX_TEXT_LENGTH);
}
